### ISSUE TITLE
Can we get a updated version

### ISSUE THREAD

**Issue by z1nc0r3** [ROBERT-MCDOWELL/ffmpeg-rtmfp-small-binaries-portable-all-OS#1]
Hi, thank you for providing this lightweight build of FFmpeg binaries. Can we expect an updated version of this?

**Comment by ROBERT-MCDOWELL** [comment]
Gosh, it's already 6 years?, since then I didn't maintain this repo because no time for now. Is it for hobby use or professional use you need it?

**Comment by z1nc0r3** [comment]
Actually, I'm working on a Python [plugin](https://github.com/z1nc0r3/AnyVideo-Downloader-Flow-Plugin) which kinda needs a lightweight ffmpeg binary. I tried so many ways to build a small binary but failed.

**Comment by ROBERT-MCDOWELL** [comment]
on windows, linux, mac? yes it's hard to do it.

**Comment by z1nc0r3** [comment]
Windows

I'll try using https://github.com/rdp/ffmpeg-windows-build-helpers to build one.

**Comment by ROBERT-MCDOWELL** [comment]
I hope it's up to date... I will try to compile a new version if I have time...

**Comment by z1nc0r3** [comment]
Thanks, I tried that helper. Oh man, even after spending about 6 hours I got nothing.

I zipped up ffmpeg and ffprobe and added a workaround to download the binaries right through the plugin during setup. It’s working well for now!

I'll close the issue.

**Comment by ROBERT-MCDOWELL** [comment]
- I zipped up ffmpeg and ffprobe and added a workaround to download the binaries right through the plugin during setup.
I don't catch it. describe it please..

**Comment by z1nc0r3** [comment]
So, the reason I try to find small binaries is that I have to include them in the plugin zip. I don't want the plugin to become large.

So I compressed and made a zip file with ffmpeg.exe and ffprobe.exe and uploaded them in a GitHub repo. Then, when the user tries to use the plugin it will show a message to download that zip file and extract it inside the plugin dir.

**Comment by ROBERT-MCDOWELL** [comment]
ok but it does not explain how you compiled ffmpeg as portable?

**Comment by z1nc0r3** [comment]
I got those from https://www.gyan.dev/ffmpeg/builds/ here. The [full-build](https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.1-full_build.7z) contains _ffmpeg, ffprobe, ffplay_ binary files.

**Comment by ROBERT-MCDOWELL** [comment]
ok good to know!
